#' PSup plot code
#'
#' Print out code for correlation matrix plot
#'
#' @export
code_corr_plot <- function() {
  print(glue::glue('spearman_corrs <-'))
  print(glue::glue('  map2_df(.x = interesting_correlations$x,'))
  print(glue::glue('          .y = interesting_correlations$y,'))
  print(glue::glue('          .f = tidy_cortest,'))
  print(glue::glue('          data = my_data,'))
  print(glue::glue('          method = "spearman")'))
  print(glue::glue(''))
  print(glue::glue('spearman_corrs %>% '))
  print(glue::glue('  ggplot(aes(x = x_var, y = y_var, fill = estimate)) +'))
  print(glue::glue('  geom_tile() +'))
  print(glue::glue('  scale_x_discrete(position = "top") +'))
  print(glue::glue('  ggtext::geom_richtext(aes(label = nice_num(estimate, 2)), family = "Jost", size = 3, text.color = "black", color = NA, fill = NA) +'))
  print(glue::glue('  scale_fill_gradient2(low = light_blue, mid = "white", high = light_fire_red, '))
  print(glue::glue('                       midpoint = 0, '))
  print(glue::glue('                       limits = c(-1, 1),'))
  print(glue::glue('                       breaks = seq(-1, 1, .2),'))
  print(glue::glue('                       labels = jimbilben::nice_num(seq(-1, 1, .2), 1, remove_lead = FALSE)) +'))
  print(glue::glue('  guides(fill = guide_colorbar(title.position = "top", '))
  print(glue::glue('                               title.hjust = .5, '))
  print(glue::glue('                               barwidth = 35, '))
  print(glue::glue('                               barheight = .5)) +'))
  print(glue::glue('  labs(x = "",'))
  print(glue::glue('       y = ""'))
  print(glue::glue('  ) +'))
  print(glue::glue('  theme_default() +'))
  print(glue::glue('  theme('))
  print(glue::glue('    panel.background = element_blank(),'))
  print(glue::glue('    panel.grid = element_blank(),'))
  print(glue::glue('    panel.border = element_blank(),'))
  print(glue::glue('    axis.text.x.top = ggtext::element_markdown(angle = 45, vjust = 0, hjust = 0),'))
  print(glue::glue('    legend.position = "bottom",'))
  print(glue::glue('    axis.text = ggtext::element_markdown(family = "Jost"),'))
  print(glue::glue('    legend.text = element_text(family = "Jost", size = 9, hjust = .5),'))
  print(glue::glue('    legend.title = element_text(family = "Jost", size = 10, hjust = .5),'))
  print(glue::glue('    plot.title = ggtext::element_markdown(family = "Jost"),'))
  print(glue::glue('    plot.subtitle = ggtext::element_markdown(family = "Jost"),'))
  print(glue::glue('    plot.title.position = "plot",'))
  print(glue::glue('    axis.ticks = element_blank(),'))
  print(glue::glue('    axis.line = element_blank()'))
  print(glue::glue('  )'))
}
