#' Theme Jimbilben
#'
#' A good theme with a grey panel background. All text elements are ggtext::element_markdown()
#' @param base_size Base size of text - defaults to 12
#' @param base_family Overall font family - defaults to Jost
#' @param border_line_color Color for the border around the plot - defaults to grey95
#' @param grid_line_color Color for the grid lines - defaults to grey95
#' @param x_ticks TRUE of FALSE, whether to include x ticks or not - defaults to FALSE
#' @param y_ticks TRUE of FALSE, whether to include y ticks or not - defaults to FALSE

#'
#' @export
#'
theme_jimbilben <- function (base_size = 11,
                             base_family = "Jost",
                             base_line_size = base_size/22,
                             base_rect_size = base_size/22,
                             border_line_color = "grey95",
                             grid_line_color = "grey95",
                             x_ticks = FALSE,
                             y_ticks = FALSE,
                             right_margin = 15) {
  half_line <- base_size/2
  t <- ggplot2::theme(line = element_line(colour = "black",
                                 size = base_line_size,
                                 linetype = 1,
                                 lineend = "butt"),
             rect = element_rect(fill = "white",
                                 colour = "black",
                                 size = base_rect_size,
                                 linetype = 1),
             text = element_text(family = base_family,
                                 face = "plain",
                                 colour = "black",
                                 size = base_size,
                                 lineheight = 0.9,
                                 hjust = 0.5,
                                 vjust = 0.5,
                                 angle = 0,
                                 margin = margin(),
                                 debug = FALSE),
             axis.line = element_blank(),
             axis.line.x = NULL,
             axis.line.y = NULL,
             axis.text = ggtext::element_markdown(size = rel(0.8),
                                                  colour = "grey10"),
             axis.text.x = ggtext::element_markdown(margin = margin(6, 0, 2, 0),
                                                    vjust = 1),
             axis.text.y = ggtext::element_markdown(margin = margin(0, 4, 0, 0),
                                                    vjust = .5,
                                                    hjust = 1),
             axis.text.x.top = ggtext::element_markdown(margin = margin(b = 0.8 * half_line/2),
                                                        hjust = 1),
             axis.text.y.right = ggtext::element_markdown(margin = margin(l = 0.8 * half_line/2),
                                                          hjust = 0),
             axis.ticks.x = if(x_ticks == FALSE) {element_blank()} else{element_line(colour = grid_line_color)},
             axis.ticks.y = if(y_ticks == FALSE) {element_blank()} else{element_line(colour = grid_line_color)},
             axis.ticks.length = unit(half_line/2, "pt"),
             axis.ticks.length.x = NULL,
             axis.ticks.length.x.top = NULL,
             axis.ticks.length.x.bottom = NULL,
             axis.ticks.length.y = NULL,
             axis.ticks.length.y.left = NULL,
             axis.ticks.length.y.right = NULL,
             axis.title.x = ggtext::element_markdown(margin = margin(6, 0, 3, 0),
                                                     vjust = 1),
             axis.title.x.top = ggtext::element_markdown(margin = margin(b = half_line/2),
                                                         vjust = 0),
             axis.title.y = ggtext::element_markdown(angle = 90,
                                                     margin = margin(0, 5, 0, 0),
                                                     vjust = .5),
             axis.title.y.right = ggtext::element_markdown(angle = -90,
                                                           margin = margin(l = half_line/2), vjust = 0),
             legend.background = element_rect(colour = NA),
             legend.spacing = unit(2 * half_line, "pt"),
             legend.spacing.x = NULL,
             legend.spacing.y = NULL,
             legend.margin = margin(0, 0, 0, 0),
             legend.key = element_rect(fill = NA,
                                       colour = NA),
             legend.key.size = unit(.9, "lines"),
             legend.key.height = NULL,
             legend.key.width = NULL,
             legend.text = ggtext::element_markdown(size = rel(0.85),
                                                    color = "grey10",
                                                    vjust = .075),
             legend.text.align = NULL,
             legend.title = ggtext::element_markdown(hjust = 0,
                                                     vjust = .075,
                                                     size = rel(.925)),
             legend.title.align = NULL,
             legend.position = "bottom",
             legend.direction = NULL,
             legend.justification = "center",
             legend.box = NULL,
             legend.box.margin = margin(0, 0, 0, 0, "cm"),
             legend.box.background = element_blank(),
             legend.box.spacing = unit(2 * half_line, "pt"),
             panel.background = element_rect(fill = NA,
                                             colour = NA),
             panel.border = element_rect(color = border_line_color,
                                         fill = NA,
                                         size = base_line_size * 1.33),
             panel.grid = element_line(colour = grid_line_color),
             panel.grid.minor = element_line(size = rel(0.5)),
             panel.spacing = unit(half_line, "pt"),
             panel.spacing.x = NULL,
             panel.spacing.y = NULL,
             panel.ontop = FALSE,
             strip.background = element_rect(fill = NA,
                                             colour = NA),
             strip.text = ggtext::element_markdown(colour = "black",
                                                   size = rel(0.95),
                                                   margin = margin(0.8 * half_line, 0.8 * half_line, 0.8 * half_line, 0.8 * half_line)),
             strip.text.x = NULL,
             strip.text.y = ggtext::element_markdown(angle = -90),
             strip.text.y.left = ggtext::element_markdown(angle = 90),
             strip.placement = "inside",
             strip.placement.x = NULL,
             strip.placement.y = NULL,
             strip.switch.pad.grid = unit(half_line/2,
                                          "pt"),
             strip.switch.pad.wrap = unit(half_line/2, "pt"),
             plot.background = element_rect(colour = "white"),
             plot.title = ggtext::element_markdown(size = rel(1.15),
                                                   hjust = 0,
                                                   vjust = 1,
                                                   margin = margin(b = half_line)),
             plot.title.position = "plot",
             plot.subtitle = ggtext::element_markdown(hjust = 0,
                                                      vjust = 1,
                                                      margin = margin(1, 1, 8, 1)),
             plot.caption = ggtext::element_markdown(size = rel(0.8),
                                                     hjust = 1,
                                                     vjust = 1,
                                                     margin = margin(2, 0, 0, 0)),
             plot.caption.position = "panel",
             plot.tag = ggtext::element_markdown(size = rel(1.15),
                                                 hjust = 0.5,
                                                 vjust = 0.5,
                                                 margin = margin(0, 0, 5, 0)),
             plot.tag.position = "top",
             plot.margin = margin(5,
                                  right_margin,
                                  5,
                                  5),
             complete = TRUE)
  #ggplot_global$theme_all_null %+replace% t
}
